# Generated by Django 3.0.4 on 2020-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('1', 'Teacher'), ('2', ' Student')], default='1 - Teacher', max_length=100),
        ),
    ]
