# Generated by Django 3.0.4 on 2020-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200419_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.CharField(choices=[('Teacher', '1 - Teacher'), ('Student', ' 2 - Student')], default='1 - Teacher', max_length=100),
        ),
    ]
