# Generated by Django 3.0.4 on 2020-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200419_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yeargroup',
            field=models.CharField(choices=[('Year 12', 'Y12'), ('Year 13', ' Y13')], default='Y13', max_length=50),
        ),
    ]
