# Generated by Django 3.0.4 on 2020-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_yeargroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='yeargroup',
            field=models.CharField(choices=[('N/A', 'Teacher'), ('Year 12', 'Y12'), ('Year 13', ' Y13')], default='Teacher', max_length=50),
        ),
    ]
