# Generated by Django 3.0.4 on 2020-04-23 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
